# ----- Application Deployment -----

apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-api-deployment
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: student-api

  template:
    metadata:
      labels:
        app: student-api

    spec:

      initContainers:
        - name: wait-for-db
          image: {{ .Values.db.image }}
          command:
            - sh
            - -c
            - |
              until pg_isready -h {{ .Values.api.config.DB_HOST }} -p {{ .Values.api.config.DB_PORT }} -U $POSTGRES_USER; do
                echo "Waiting for database..."
                sleep 2
              done
              echo "Database ready"

          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: student-api-secret
                  key: POSTGRES_USER

      containers:
        - name: student-api
          image: "{{ .Values.api.image }}:{{ .Values.api.tag }}"
          imagePullPolicy: {{ .Values.api.pullPolicy }}

          ports:
            - containerPort: {{ .Values.api.port }}

          env:
            - name: DB_URL
              value: "jdbc:postgresql://{{ .Values.api.config.DB_HOST }}:{{ .Values.api.config.DB_PORT }}/{{ .Values.db.config.POSTGRES_DB }}"

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: student-api-secret
                  key: POSTGRES_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: student-api-secret
                  key: POSTGRES_PASSWORD

          readinessProbe:
            httpGet:
              path: /api/v1/healthcheck
              port: {{ .Values.api.port }}
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5

          livenessProbe:
            httpGet:
              path: /api/v1/healthcheck
              port: {{ .Values.api.port }}
            initialDelaySeconds: 120
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5

---

# ----- Application Service -----

apiVersion: v1
kind: Service
metadata:
  name: student-api-service
  labels:
    app: student-api
spec:
  selector:
    app: student-api
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.api.port }}
      protocol: TCP
  type: ClusterIP
