name: Student API CI/CD Pipeline

on:
  workflow_dispatch:

  push:
    branches:
      - lvl04
      - lvl05
      - master
    paths:
      - "src/**"
      - "pom.xml"
      - "Dockerfile"
      - "Makefile"
      - "helm/**"

  pull_request:
    branches:
      - master
    paths:
      - "src/**"
      - "pom.xml"
      - "Dockerfile"
      - "Makefile"

env:
  VERSION: ${{ secrets.SEMVER_VERSION }}

jobs:

  ci:
    name: Build, Test, Lint and Push Docker Image
    runs-on: self-hosted

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build API
        run: make build

      - name: Run Tests
        run: make test

      - name: Lint Code
        run: make lint

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker Build and Push
        run: |
          make docker-test
          make docker-build VERSION=${VERSION}
          make docker-push VERSION=${VERSION}

  cd:
    name: Update Helm Values for GitOps
    needs: ci
    runs-on: self-hosted

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update Helm Image Tag
        run: |
          sed -i '' "s/tag:.*/tag: \"${VERSION}\"/" helm/student-api/values.yaml

      - name: Commit Updated Helm Values
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add helm/student-api/values.yaml
          git commit -m "ci: update image tag to ${VERSION}" || echo "No changes"
          git push